evershop:
  database:

    # datasource, must by one of [sqlite, mysql]
    datasource: sqlite
    mysql:
      hostname: 127.0.0.1
      username: test
      password: test
      db_name: test
      prefix: es_
      port: 3306
    sqlite: 
      filename: database.db
      prefix: es_
  linkMaterial: redstone
  destroyMaterial: golden_axe

  # Available translations of shop items. 
  #   Add all languages that your players *may* use. When the player interact with shops, it will display item
  #   names using the same language with client. (If it's in this list)
  # 
  # WARNING: all languages except en_us will cause the plugin download language files from mojang, because we 
  #   cannot distribute them. If you want to avoid downloading, you can download the language files manually, 
  #   and put them in plugins/EverShop/i18n/items folder, before you add entries here and start your server.
  item_translation: [en_us]
  
  # Available translations for transaction messages
  #   The plugin will use all files from plugins/EverShop/i18n/msgs to translate transaction messages, so you don't
  #   need to indicate message translation files here. If you want to make your own translations, just copy en_us.yml
  #   to some_language.yml, and then edit values in it. 
  
  # Default language
  #   If the client language is not supported, this language will use as a fallback translation.
  # Make sure this language is available in both item translation and message translation!
  default_translation: en_us

  #TODO change to lang files
  alias:
    BUY: 
      - 出售
      - 卖
    SELL: 收购
  tax:
    consumption_tax:
      type: by_transaction_progressive # none, static, by_balance, by_transaction_static, by_transaction_progressive
      tiers: 
        "0": 0.01
        "10": 0.02
        "20": 0.03
        "50": 0.04
        "100": 0.06
        "500": 0.08
        "1000": 0.1
    income_tax:
      type: by_balance
      tiers:
        "0": 0
        "100": 0.01
        "1000": 0.02
        "2000": 0.03
        "5000": 0.04
        "10000": 0.05
        "20000": 0.07
        "50000": 0.1