
name: GitHub Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build EverShop
      run: mvn clean package 
    - name: FTP Deploy
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ftp://ci.djytw.cn
        user: djytw_ci
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: target/
        remoteDir: site/wwwroot/maven-repository/com/evermc/evershop/
    - uses: actions/upload-artifact@v2
      with:
        name: EverShop
        path: target/
