# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Apache Maven Central
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: maven-djytw
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
    - name: Get Buildtools
      run: wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    - name: Build Spigot
      run: java -jar BuildTools.jar --rev 1.14.4
    - name: Publish to Apache Maven Central
      run: mvn clean deploy 
      env:
        MAVEN_USERNAME: ${{ secrets.maven_djytw_user }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.maven_djytw_pwd }}
    - uses: actions/upload-artifact@v1
      with:
        name: Upload artifact
        path: target/EverShop-1.0.jar
