
name: GitHub Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build EverShop
      run: |
        mvn clean install 
    - uses: actions/upload-artifact@v2
      with:
        name: EverShop
        path: target/
