# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Apache Maven Central
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: maven-djytw
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
    # cb 1.14 cache
    - name: Find cache of CraftBukkit 1.14.4
      id: cb-1-14-4
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository/org/spigotmc/spigot/1.14.4-R0.1-SNAPSHOT
        key: ${{ runner.os }}-maven-CB1.14.4
    # build cb 1.14
    - name: Build CraftBukkit-1.14.4
      if: steps.cb-1-14-4.outputs.cache-hit != 'true'
      run: |
        wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        java -jar BuildTools.jar --rev 1.14.4
    # cb 1.15 cache
    - name: Find cache of CraftBukkit 1.15.2
      id: cb-1-15-2
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository/org/spigotmc/spigot/1.15.2-R0.1-SNAPSHOT
        key: ${{ runner.os }}-maven-CB1.15.2
    # build cb 1.15
    - name: Build CraftBukkit-1.15.2
      if: steps.cb-1-15-2.outputs.cache-hit != 'true'
      run: |
        wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        java -jar BuildTools.jar --rev 1.15.2
    # build master
    - name: Build & deploy EverShop
      run: mvn clean deploy 
      env:
        MAVEN_USERNAME: ${{ secrets.maven_djytw_user }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.maven_djytw_pwd }}
    - uses: actions/upload-artifact@v1
      with:
        name: Upload artifact
        path: target/EverShop-1.0.jar
